__author__ = 'Daniil Leksin'
# -*- coding: utf-8 -*-

###########################################################################
##
##
##
##
###########################################################################
global user_metrics
global session_metrics

#
user_metrics = {
    "ga:userType": {
        "type": "bool",
        "view": "Dimensions",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_usertype"],
        "value": False},
    "ga:sessionCount": {
        "type": "bool",
        "view": "Dimensions",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_sessioncount"],
        "value": False},
    "ga:daysSinceLastSession": {
        "type": "bool",
        "view": "Dimensions",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_dayssincelastsession"],
        "value": False},
    "ga:userDefinedValue": {
        "type": "bool",
        "view": "Dimensions",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_userdefinedvalue"],
        "value": False},
    "ga:users": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_users"],
        "value": False},
    "ga:newUsers": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=user&jump=ga_newusers"],
        "value": False},
    "ga:percentNewSessions": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", ""],
        "value": False},
}

#
session_metrics = {
    "ga:sessionDurationBucket": {
        "type": "bool",
        "view": "Dimensions",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessiondurationbucket"],
        "value": False},
    "ga:sessions": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessions"],
        "value": False},
    "ga:bounces": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_bounces"],
        "value": False},
    "ga:sessionDuration": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessionduration"],
        "value": False},
    "ga:hits": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_hits"],
        "value": False},
    "ga:bounceRate": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_bounces"],
        "value": False},
    "ga:avgSessionDuration": {
        "type": "bool",
        "view": "Metrics",
        "html": ["Default/default.html", "https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_avgsessionduration"],
        "value": False},
}

traffic_source_metrics = {
    'ga:adContent': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:medium': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:referralPath': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:socialNetwork': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:keyword': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:campaign': {
       "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:source': {
       "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:hasSocialSourceReferral': {
       "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:sourceMedium': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:fullReferrer': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:organicSearches': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Metrics'}
}

adwords_metrics = {
    'ga:adTargetingType': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adSlot': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adwordsCustomerID': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adKeywordMatchType': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adMatchType': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adDestinationUrl': {
       "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adMatchedQuery': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:adFormat': {
        "html": "Default/default.html",
        'value': False,
        'view': 'Dimensions'},
    'ga:isTrueViewVideoAd': {
        'html': 'isTrueViewVideoAdPage/isTrueViewVideoAdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adGroup': {
        'html': 'adGroupPage/adGroupPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adwordsCampaignID': {
        'html': 'adwordsCampaignIDPage/adwordsCampaignIDPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adDistributionNetwork': {
        'html': 'adDistributionNetworkPage/adDistributionNetworkPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adwordsCriteriaID': {
        'html': 'adwordsCriteriaIDPage/adwordsCriteriaIDPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adwordsCreativeID': {
        'html': 'adwordsCreativeIDPage/adwordsCreativeIDPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adDisplayUrl': {
        'html': 'adDisplayUrlPage/adDisplayUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adSlotPosition': {
        'html': 'adSlotPositionPage/adSlotPositionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adPlacementDomain': {
        'html': 'adPlacementDomainPage/adPlacementDomainPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adPlacementUrl': {
        'html': 'adPlacementUrlPage/adPlacementUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adTargetingOption': {
        'html': 'adTargetingOptionPage/adTargetingOptionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adwordsAdGroupID': {
        'html': 'adwordsAdGroupIDPage/adwordsAdGroupIDPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:adClicks': {
        'html': 'adClicksPage/adClicksPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:impressions': {
        'html': 'impressionsPage/impressionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adCost': {
        'html': 'adCostPage/adCostPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:margin': {
        'html': 'marginPage/marginPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:CTR': {
        'html': 'CTRPage/CTRPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:CPM': {
        'html': 'CPMPage/CPMPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:CPC': {
        'html': 'CPCPage/CPCPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:costPerConversion': {
        'html': 'costPerConversionPage/costPerConversionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:costPerTransaction': {
        'html': 'costPerTransactionPage/costPerTransactionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:RPC': {
        'html': 'RPCPage/RPCPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:costPerGoalConversion': {
        'html': 'costPerGoalConversionPage/costPerGoalConversionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:ROI': {
        'html': 'ROIPage/ROIPage.html',
        'value': False,
        'view': 'Metrics'}
}

goal_conversions_metrics = {
    'ga:goalCompletionLocation': {
        'html': 'goalCompletionLocationPage/goalCompletionLocationPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:goalPreviousStep2': {
        'html': 'goalPreviousStep2Page/goalPreviousStep2Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:goalPreviousStep3': {
        'html': 'goalPreviousStep3Page/goalPreviousStep3Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:goalPreviousStep1': {
        'html': 'goalPreviousStep1Page/goalPreviousStep1Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:goalCompletionsAll': {
        'html': 'goalCompletionsAllPage/goalCompletionsAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXValue': {
        'html': 'goalXXValuePage/goalXXValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalValuePerVisit': {
        'html': 'goalValuePerVisitPage/goalValuePerVisitPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalConversionRateAll': {
        'html': 'goalConversionRateAllPage/goalConversionRateAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXAbandonRate': {
        'html': 'goalXXAbandonRatePage/goalXXAbandonRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalValueAll': {
        'html': 'goalValueAllPage/goalValueAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXCompletions': {
        'html': 'goalXXCompletionsPage/goalXXCompletionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXStarts': {
        'html': 'goalXXStartsPage/goalXXStartsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXAbandons': {
        'html': 'goalXXAbandonsPage/goalXXAbandonsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalValuePerSession': {
        'html': 'goalValuePerSessionPage/goalValuePerSessionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalAbandonRateAll': {
        'html': 'goalAbandonRateAllPage/goalAbandonRateAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalAbandonsAll': {
        'html': 'goalAbandonsAllPage/goalAbandonsAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalXXConversionRate': {
        'html': 'goalXXConversionRatePage/goalXXConversionRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalStartsAll': {
        'html': 'goalStartsAllPage/goalStartsAllPage.html',
        'value': False,
        'view': 'Metrics'}
}

platform_device_metrics = {
    'ga:mobileDeviceBranding': {
        'html': 'mobileDeviceBrandingPage/mobileDeviceBrandingPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:mobileDeviceInfo': {
        'html': 'mobileDeviceInfoPage/mobileDeviceInfoPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:deviceCategory': {
        'html': 'deviceCategoryPage/deviceCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:operatingSystem': {
        'html': 'operatingSystemPage/operatingSystemPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:mobileInputSelector': {
        'html': 'mobileInputSelectorPage/mobileInputSelectorPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:browser': {
        'html': 'browserPage/browserPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:operatingSystemVersion': {
        'html': 'operatingSystemVersionPage/operatingSystemVersionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:mobileDeviceMarketingName': {
        'html': 'mobileDeviceMarketingNamePage/mobileDeviceMarketingNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:mobileDeviceModel': {
        'html': 'mobileDeviceModelPage/mobileDeviceModelPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:browserVersion': {
        'html': 'browserVersionPage/browserVersionPage.html',
        'value': False,
        'view': 'Dimensions'}
}

geo_network_metrics = {
    'ga:city': {
        'html': 'cityPage/cityPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:longitude': {
        'html': 'longitudePage/longitudePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:country': {
        'html': 'countryPage/countryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:region': {
        'html': 'regionPage/regionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:networkDomain': {
        'html': 'networkDomainPage/networkDomainPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:metro': {
        'html': 'metroPage/metroPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:subContinent': {
        'html': 'subContinentPage/subContinentPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:latitude': {
        'html': 'latitudePage/latitudePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:continent': {
        'html': 'continentPage/continentPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:networkLocation': {
        'html': 'networkLocationPage/networkLocationPage.html',
        'value': False,
        'view': 'Dimensions'}
}

system_metrics = {
    'ga:sourcePropertyDisplayName': {
        'html': 'sourcePropertyDisplayNamePage/sourcePropertyDisplayNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:flashVersion': {
        'html': 'flashVersionPage/flashVersionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:language': {
        'html': 'languagePage/languagePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:sourcePropertyTrackingId': {
        'html': 'sourcePropertyTrackingIdPage/sourcePropertyTrackingIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:javaEnabled': {
        'html': 'javaEnabledPage/javaEnabledPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:screenColors': {
        'html': 'screenColorsPage/screenColorsPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:screenResolution': {
        'html': 'screenResolutionPage/screenResolutionPage.html',
        'value': False,
        'view': 'Dimensions'}
}

social_activities_metrics = {
    'ga:socialActivityTimestamp': {
        'html': 'socialActivityTimestampPage/socialActivityTimestampPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityAction': {
        'html': 'socialActivityActionPage/socialActivityActionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityTagsSummary': {
        'html': 'socialActivityTagsSummaryPage/socialActivityTagsSummaryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityUserProfileUrl': {
        'html': 'socialActivityUserProfileUrlPage/socialActivityUserProfileUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityEndorsingUrl': {
        'html': 'socialActivityEndorsingUrlPage/socialActivityEndorsingUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityNetworkAction': {
        'html': 'socialActivityNetworkActionPage/socialActivityNetworkActionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityPost': {
        'html': 'socialActivityPostPage/socialActivityPostPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityUserHandle': {
        'html': 'socialActivityUserHandlePage/socialActivityUserHandlePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityUserPhotoUrl': {
        'html': 'socialActivityUserPhotoUrlPage/socialActivityUserPhotoUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityContentUrl': {
        'html': 'socialActivityContentUrlPage/socialActivityContentUrlPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivityDisplayName': {
        'html': 'socialActivityDisplayNamePage/socialActivityDisplayNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialActivities': {
        'html': 'socialActivitiesPage/socialActivitiesPage.html',
        'value': False,
        'view': 'Metrics'}
}

page_tracking_metrics = {
    'ga:pagePathLevel1': {
        'html': 'pagePathLevel1Page/pagePathLevel1Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:pagePathLevel3': {
        'html': 'pagePathLevel3Page/pagePathLevel3Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:pagePathLevel2': {
        'html': 'pagePathLevel2Page/pagePathLevel2Page.html',
        'value': False, 'view': 'Dimensions'},
    'ga:pagePathLevel4': {
        'html': 'pagePathLevel4Page/pagePathLevel4Page.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:hostname': {
        'html': 'hostnamePage/hostnamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:pageTitle': {
        'html': 'pageTitlePage/pageTitlePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:pagePath': {
        'html': 'pagePathPage/pagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nextPagePath': {
        'html': 'nextPagePathPage/nextPagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:exitPagePath': {
        'html': 'exitPagePathPage/exitPagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:secondPagePath': {
        'html': 'secondPagePathPage/secondPagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:landingPagePath': {
        'html': 'landingPagePathPage/landingPagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:pageDepth': {
        'html': 'pageDepthPage/pageDepthPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:previousPagePath': {
        'html': 'previousPagePathPage/previousPagePathPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:exits': {
        'html': 'exitsPage/exitsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgTimeOnPage': {
        'html': 'avgTimeOnPagePage/avgTimeOnPagePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniquePageviews': {
        'html': 'uniquePageviewsPage/uniquePageviewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageviewsPerSession': {
        'html': 'pageviewsPerSessionPage/pageviewsPerSessionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:exitRate': {
        'html': 'exitRatePage/exitRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:entranceRate': {
        'html': 'entranceRatePage/entranceRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:timeOnPage': {
        'html': 'timeOnPagePage/timeOnPagePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageviews': {
        'html': 'pageviewsPage/pageviewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageValue': {
        'html': 'pageValuePage/pageValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:entrances': {
        'html': 'entrancesPage/entrancesPage.html',
        'value': False,
        'view': 'Metrics'}
}

content_grouping_metrics = {
    'ga:previousContentGroupXX': {
        'html': 'previousContentGroupXXPage/previousContentGroupXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:contentGroupXX': {
        'html': 'contentGroupXXPage/contentGroupXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nextContentGroupXX': {
        'html': 'nextContentGroupXXPage/nextContentGroupXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:contentGroupUniqueViewsXX': {
        'html': 'contentGroupUniqueViewsXXPage/contentGroupUniqueViewsXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:landingContentGroupXX': {
        'html': 'landingContentGroupXXPage/landingContentGroupXXPage.html',
        'value': False,
        'view': 'Metrics'}
}

internal_search_metrics = {
    'ga:searchStartPage': {
        'html': 'searchStartPagePage/searchStartPagePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchKeywordRefinement': {
        'html': 'searchKeywordRefinementPage/searchKeywordRefinementPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchUsed': {
        'html': 'searchUsedPage/searchUsedPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchCategory': {
        'html': 'searchCategoryPage/searchCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchKeyword': {
        'html': 'searchKeywordPage/searchKeywordPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchDestinationPage': {
        'html': 'searchDestinationPagePage/searchDestinationPagePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:searchExitRate': {
        'html': 'searchExitRatePage/searchExitRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:percentSearchRefinements': {
        'html': 'percentSearchRefinementsPage/percentSearchRefinementsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgSearchDuration': {
        'html': 'avgSearchDurationPage/avgSearchDurationPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgSearchResultViews': {
        'html': 'avgSearchResultViewsPage/avgSearchResultViewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgSearchDepth': {
        'html': 'avgSearchDepthPage/avgSearchDepthPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchVisits': {
        'html': 'searchVisitsPage/searchVisitsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:percentSessionsWithSearch': {
        'html': 'percentSessionsWithSearchPage/percentSessionsWithSearchPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchDepth': {
        'html': 'searchDepthPage/searchDepthPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchResultViews': {
        'html': 'searchResultViewsPage/searchResultViewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchDuration': {
        'html': 'searchDurationPage/searchDurationPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchRefinements': {
        'html': 'searchRefinementsPage/searchRefinementsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchUniques': {
        'html': 'searchUniquesPage/searchUniquesPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchGoalXXConversionRate': {
        'html': 'searchGoalXXConversionRatePage/searchGoalXXConversionRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:goalValueAllPerSearch': {
        'html': 'goalValueAllPerSearchPage/goalValueAllPerSearchPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:percentVisitsWithSearch': {
        'html': 'percentVisitsWithSearchPage/percentVisitsWithSearchPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchSessions':
        {'html': 'searchSessionsPage/searchSessionsPage.html',
         'value': False,
         'view': 'Metrics'},
    'ga:searchGoalConversionRateAll': {
        'html': 'searchGoalConversionRateAllPage/searchGoalConversionRateAllPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:searchExits': {
        'html': 'searchExitsPage/searchExitsPage.html',
        'value': False,
        'view': 'Metrics'}
}

site_speed_metrics = {
    'ga:domInteractiveTime': {
        'html': 'domInteractiveTimePage/domInteractiveTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgDomainLookupTime': {
        'html': 'avgDomainLookupTimePage/avgDomainLookupTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgPageLoadTime': {
        'html': 'avgPageLoadTimePage/avgPageLoadTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageLoadTime': {
        'html': 'pageLoadTimePage/pageLoadTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgDomInteractiveTime': {
        'html': 'avgDomInteractiveTimePage/avgDomInteractiveTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgServerConnectionTime': {
        'html': 'avgServerConnectionTimePage/avgServerConnectionTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgPageDownloadTime': {
        'html': 'avgPageDownloadTimePage/avgPageDownloadTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:serverConnectionTime': {
        'html': 'serverConnectionTimePage/serverConnectionTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:redirectionTime': {
        'html': 'redirectionTimePage/redirectionTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgRedirectionTime': {
        'html': 'avgRedirectionTimePage/avgRedirectionTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgDomContentLoadedTime': {
        'html': 'avgDomContentLoadedTimePage/avgDomContentLoadedTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:domContentLoadedTime': {
        'html': 'domContentLoadedTimePage/domContentLoadedTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:serverResponseTime': {
        'html': 'serverResponseTimePage/serverResponseTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgServerResponseTime': {
        'html': 'avgServerResponseTimePage/avgServerResponseTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:domainLookupTime': {
        'html': 'domainLookupTimePage/domainLookupTimePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:speedMetricsSample': {
        'html': 'speedMetricsSamplePage/speedMetricsSamplePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:domLatencyMetricsSample': {
        'html': 'domLatencyMetricsSamplePage/domLatencyMetricsSamplePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageLoadSample': {
        'html': 'pageLoadSamplePage/pageLoadSamplePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:pageDownloadTime': {
        'html': 'pageDownloadTimePage/pageDownloadTimePage.html',
        'value': False,
        'view': 'Metrics'}
}

app_tracking_metrics = {
    'ga:screenName': {
        'html': 'screenNamePage/screenNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:screenDepth': {
        'html': 'screenDepthPage/screenDepthPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:appName': {
        'html': 'appNamePage/appNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:exitScreenName': {
        'html': 'exitScreenNamePage/exitScreenNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:appId': {
        'html': 'appIdPage/appIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:appVersion': {
        'html': 'appVersionPage/appVersionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:appInstallerId': {
        'html': 'appInstallerIdPage/appInstallerIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:landingScreenName': {
        'html': 'landingScreenNamePage/landingScreenNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:screenviews': {
        'html': 'screenviewsPage/screenviewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniqueScreenviews': {
        'html': 'uniqueScreenviewsPage/uniqueScreenviewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:timeOnScreen': {
        'html': 'timeOnScreenPage/timeOnScreenPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniqueAppviews': {
        'html': 'uniqueAppviewsPage/uniqueAppviewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgScreenviewDuration': {
        'html': 'avgScreenviewDurationPage/avgScreenviewDurationPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:screenviewsPerSession': {
        'html': 'screenviewsPerSessionPage/screenviewsPerSessionPage.html',
        'value': False,
        'view': 'Metrics'}
}

event_tracking_metrics = {
    'ga:eventLabel': {
        'html': 'eventLabelPage/eventLabelPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:eventCategory': {
        'html': 'eventCategoryPage/eventCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:eventAction': {
        'html': 'eventActionPage/eventActionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:avgEventValue': {
        'html': 'avgEventValuePage/avgEventValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:sessionsWithEvent': {
        'html': 'sessionsWithEventPage/sessionsWithEventPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:eventValue': {
        'html': 'eventValuePage/eventValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:totalEvents': {
        'html': 'totalEventsPage/totalEventsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:eventsPerSessionWithEvent': {
        'html': 'eventsPerSessionWithEventPage/eventsPerSessionWithEventPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniqueEvents': {
        'html': 'uniqueEventsPage/uniqueEventsPage.html',
        'value': False,
        'view': 'Metrics'}
}

ecommerce_metrics = {
    'ga:productName': {
        'html': 'productNamePage/productNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:transactionId': {
        'html': 'transactionIdPage/transactionIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:affiliation': {
        'html': 'affiliationPage/affiliationPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productBrand': {
        'html': 'productBrandPage/productBrandPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productCategoryHierarchy': {
        'html': 'productCategoryHierarchyPage/productCategoryHierarchyPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productListPosition': {
        'html': 'productListPositionPage/productListPositionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productCategoryLevelXX': {
        'html': 'productCategoryLevelXXPage/productCategoryLevelXXPage.html',
        'value': False, 'view': 'Dimensions'},
    'ga:productSku': {
        'html': 'productSkuPage/productSkuPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:shoppingStage': {
        'html': 'shoppingStagePage/shoppingStagePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:orderCouponCode': {
        'html': 'orderCouponCodePage/orderCouponCodePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:daysToTransaction': {
        'html': 'daysToTransactionPage/daysToTransactionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productCouponCode': {
        'html': 'productCouponCodePage/productCouponCodePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productVariant': {
        'html': 'productVariantPage/productVariantPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productListName': {
        'html': 'productListNamePage/productListNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:sessionsToTransaction': {
        'html': 'sessionsToTransactionPage/sessionsToTransactionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:internalPromotionName': {
        'html': 'internalPromotionNamePage/internalPromotionNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:internalPromotionPosition': {
        'html': 'internalPromotionPositionPage/internalPromotionPositionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:internalPromotionId': {
        'html': 'internalPromotionIdPage/internalPromotionIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:currencyCode': {
        'html': 'currencyCodePage/currencyCodePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:checkoutOptions': {
        'html': 'checkoutOptionsPage/checkoutOptionsPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:internalPromotionCreative': {
        'html': 'internalPromotionCreativePage/internalPromotionCreativePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productCategory': {
        'html': 'productCategoryPage/productCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:productRevenuePerPurchase': {
        'html': 'productRevenuePerPurchasePage/productRevenuePerPurchasePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productRemovesFromCart': {
        'html': 'productRemovesFromCartPage/productRemovesFromCartPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:itemRevenue': {
        'html': 'itemRevenuePage/itemRevenuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactionTax': {
        'html': 'transactionTaxPage/transactionTaxPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:internalPromotionClicks': {
        'html': 'internalPromotionClicksPage/internalPromotionClicksPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productRefunds': {
        'html': 'productRefundsPage/productRefundsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:totalRefunds': {
        'html': 'totalRefundsPage/totalRefundsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:internalPromotionViews': {
        'html': 'internalPromotionViewsPage/internalPromotionViewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productListClicks': {
        'html': 'productListClicksPage/productListClicksPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactions': {
        'html': 'transactionsPage/transactionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:quantityRefunded': {
        'html': 'quantityRefundedPage/quantityRefundedPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productCheckouts': {
        'html': 'productCheckoutsPage/productCheckoutsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localTransactionTax': {
        'html': 'localTransactionTaxPage/localTransactionTaxPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactionsPerSession': {
        'html': 'transactionsPerSessionPage/transactionsPerSessionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productListCTR': {
        'html': 'productListCTRPage/productListCTRPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactionRevenuePerSession': {
        'html': 'transactionRevenuePerSessionPage/transactionRevenuePerSessionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:itemQuantity': {
        'html': 'itemQuantityPage/itemQuantityPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:buyToDetailRate': {
        'html': 'buyToDetailRatePage/buyToDetailRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localTransactionRevenue': {
        'html': 'localTransactionRevenuePage/localTransactionRevenuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:quantityRemovedFromCart': {
        'html': 'quantityRemovedFromCartPage/quantityRemovedFromCartPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productListViews': {
        'html': 'productListViewsPage/productListViewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactionShipping': {
        'html': 'transactionShippingPage/transactionShippingPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productRefundAmount': {
        'html': 'productRefundAmountPage/productRefundAmountPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:revenuePerTransaction': {
        'html': 'revenuePerTransactionPage/revenuePerTransactionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:internalPromotionCTR': {
        'html': 'internalPromotionCTRPage/internalPromotionCTRPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:revenuePerItem': {
        'html': 'revenuePerItemPage/revenuePerItemPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localProductRefundAmount': {
        'html': 'localProductRefundAmountPage/localProductRefundAmountPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniquePurchases': {
        'html': 'uniquePurchasesPage/uniquePurchasesPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localItemRevenue': {
        'html': 'localItemRevenuePage/localItemRevenuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:refundAmount': {
        'html': 'refundAmountPage/refundAmountPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:quantityCheckedOut': {
        'html': 'quantityCheckedOutPage/quantityCheckedOutPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localTransactionShipping': {
        'html': 'localTransactionShippingPage/localTransactionShippingPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:localRefundAmount': {
        'html': 'localRefundAmountPage/localRefundAmountPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productAddsToCart': {
        'html': 'productAddsToCartPage/productAddsToCartPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:quantityAddedToCart': {
        'html': 'quantityAddedToCartPage/quantityAddedToCartPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:productDetailViews': {
        'html': 'productDetailViewsPage/productDetailViewsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:cartToDetailRate': {
        'html': 'cartToDetailRatePage/cartToDetailRatePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:totalValue': {
        'html': 'totalValuePage/totalValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:itemsPerPurchase': {
        'html': 'itemsPerPurchasePage/itemsPerPurchasePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:transactionRevenue': {
        'html': 'transactionRevenuePage/transactionRevenuePage.html',
        'value': False,
        'view': 'Metrics'}
}

social_interaction_metrics = {
    'ga:socialEngagementType': {
        'html': 'socialEngagementTypePage/socialEngagementTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialInteractionNetworkAction': {
        'html': 'socialInteractionNetworkActionPage/socialInteractionNetworkActionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialInteractionTarget': {
        'html': 'socialInteractionTargetPage/socialInteractionTargetPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialInteractionAction': {
        'html': 'socialInteractionActionPage/socialInteractionActionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialInteractionNetwork': {
        'html': 'socialInteractionNetworkPage/socialInteractionNetworkPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:socialInteractionsPerSession': {
        'html': 'socialInteractionsPerSessionPage/socialInteractionsPerSessionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:socialInteractions': {
        'html': 'socialInteractionsPage/socialInteractionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:uniqueSocialInteractions': {
        'html': 'uniqueSocialInteractionsPage/uniqueSocialInteractionsPage.html',
        'value': False,
        'view': 'Metrics'}
}

user_timing_metrics = {
    'ga:userTimingVariable': {
        'html': 'userTimingVariablePage/userTimingVariablePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:userTimingCategory': {
        'html': 'userTimingCategoryPage/userTimingCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:userTimingLabel': {
        'html': 'userTimingLabelPage/userTimingLabelPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:userTimingSample': {
        'html': 'userTimingSamplePage/userTimingSamplePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:avgUserTimingValue': {
        'html': 'avgUserTimingValuePage/avgUserTimingValuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:userTimingValue': {
        'html': 'userTimingValuePage/userTimingValuePage.html',
        'value': False,
        'view': 'Metrics'}
}

exception_metrics = {
    'ga:exceptionsPerScreenview': {
        'html': 'exceptionsPerScreenviewPage/exceptionsPerScreenviewPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:exceptionDescription': {
        'html': 'exceptionDescriptionPage/exceptionDescriptionPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:fatalExceptions': {
        'html': 'fatalExceptionsPage/fatalExceptionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:exceptions': {
        'html': 'exceptionsPage/exceptionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:fatalExceptionsPerScreenview': {
        'html': 'fatalExceptionsPerScreenviewPage/fatalExceptionsPerScreenviewPage.html',
        'value': False,
        'view': 'Metrics'}
}


content_experiments_metrics = {
    'ga:experimentVariant': {
        'html': 'experimentVariantPage/experimentVariantPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:experimentId': {
        'html': 'experimentIdPage/experimentIdPage.html',
        'value': False,
        'view': 'Dimensions'}
}

custom_variables_columns_metrics = {
    'ga:dimensionXX': {
        'html': 'dimensionXXPage/dimensionXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:customVarNameXX': {
        'html': 'customVarNameXXPage/customVarNameXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:customVarValueXX': {
        'html': 'customVarValueXXPage/customVarValueXXPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:metricXX': {
        'html': 'metricXXPage/metricXXPage.html',
        'value': False,
        'view': 'Metrics'}
}

time_metrics = {
    'ga:isoYear': {
        'html': 'isoYearPage/isoYearPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nthHour': {
        'html': 'nthHourPage/nthHourPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nthWeek': {
        'html': 'nthWeekPage/nthWeekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dayOfWeek': {
        'html': 'dayOfWeekPage/dayOfWeekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nthMonth': {
        'html': 'nthMonthPage/nthMonthPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dateHour': {
        'html': 'dateHourPage/dateHourPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dayOfWeekName': {
        'html': 'dayOfWeekNamePage/dayOfWeekNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nthDay': {
        'html': 'nthDayPage/nthDayPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:yearWeek': {
        'html': 'yearWeekPage/yearWeekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:year': {
        'html': 'yearPage/yearPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:isoWeek': {
        'html': 'isoWeekPage/isoWeekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:month': {
        'html': 'monthPage/monthPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:date': {
        'html': 'datePage/datePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:day': {
        'html': 'dayPage/dayPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:hour': {
        'html': 'hourPage/hourPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:isoYearIsoWeek': {
        'html': 'isoYearIsoWeekPage/isoYearIsoWeekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:minute': {
        'html': 'minutePage/minutePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:nthMinute': {
        'html': 'nthMinutePage/nthMinutePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:week': {
        'html': 'weekPage/weekPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:yearMonth': {
        'html': 'yearMonthPage/yearMonthPage.html',
        'value': False,
        'view': 'Dimensions'}
}

double_click_campaign_manager_metrics = {
    'ga:dcmClickRenderingId': {
        'html': 'dcmClickRenderingIdPage/dcmClickRenderingIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAdId': {
        'html': 'dcmClickAdIdPage/dcmClickAdIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickSitePlacementId': {
        'html': 'dcmClickSitePlacementIdPage/dcmClickSitePlacementIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightActivityId': {
        'html': 'dcmFloodlightActivityIdPage/dcmFloodlightActivityIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventSiteId': {
        'html': 'dcmLastEventSiteIdPage/dcmLastEventSiteIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAdId': {
        'html': 'dcmLastEventAdIdPage/dcmLastEventAdIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventSitePlacement': {
        'html': 'dcmLastEventSitePlacementPage/dcmLastEventSitePlacementPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAdvertiserId': {
        'html': 'dcmLastEventAdvertiserIdPage/dcmLastEventAdvertiserIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickSite': {
        'html': 'dcmClickSitePage/dcmClickSitePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCreativeVersion': {
        'html': 'dcmClickCreativeVersionPage/dcmClickCreativeVersionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCampaignId': {
        'html': 'dcmLastEventCampaignIdPage/dcmLastEventCampaignIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAdvertiser': {
        'html': 'dcmLastEventAdvertiserPage/dcmLastEventAdvertiserPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAdTypeId': {
        'html': 'dcmLastEventAdTypeIdPage/dcmLastEventAdTypeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightActivityAndGroup': {
        'html': 'dcmFloodlightActivityAndGroupPage/dcmFloodlightActivityAndGroupPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCreativeType': {
        'html': 'dcmLastEventCreativeTypePage/dcmLastEventCreativeTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAdType': {
        'html': 'dcmClickAdTypePage/dcmClickAdTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCampaign': {
        'html': 'dcmLastEventCampaignPage/dcmLastEventCampaignPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventSite': {
        'html': 'dcmLastEventSitePage/dcmLastEventSitePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightSpotId': {
        'html': 'dcmFloodlightSpotIdPage/dcmFloodlightSpotIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventSitePlacementId': {
        'html': 'dcmLastEventSitePlacementIdPage/dcmLastEventSitePlacementIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCreativeTypeId': {
        'html': 'dcmLastEventCreativeTypeIdPage/dcmLastEventCreativeTypeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickSpotId': {
        'html': 'dcmClickSpotIdPage/dcmClickSpotIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCreative': {
        'html': 'dcmClickCreativePage/dcmClickCreativePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCampaign': {
        'html': 'dcmClickCampaignPage/dcmClickCampaignPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAdvertiser': {
        'html': 'dcmClickAdvertiserPage/dcmClickAdvertiserPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightActivity': {
        'html': 'dcmFloodlightActivityPage/dcmFloodlightActivityPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAd': {
        'html': 'dcmLastEventAdPage/dcmLastEventAdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickSiteId': {
        'html': 'dcmClickSiteIdPage/dcmClickSiteIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAd': {
        'html': 'dcmClickAdPage/dcmClickAdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCreativeVersion': {
        'html': 'dcmLastEventCreativeVersionPage/dcmLastEventCreativeVersionPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAdTypeId': {
        'html': 'dcmClickAdTypeIdPage/dcmClickAdTypeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightActivityGroupId': {
        'html': 'dcmFloodlightActivityGroupIdPage/dcmFloodlightActivityGroupIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightAdvertiserId': {
        'html': 'dcmFloodlightAdvertiserIdPage/dcmFloodlightAdvertiserIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAttributionType': {
        'html': 'dcmLastEventAttributionTypePage/dcmLastEventAttributionTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventAdType': {
        'html': 'dcmLastEventAdTypePage/dcmLastEventAdTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCreativeId': {
        'html': 'dcmLastEventCreativeIdPage/dcmLastEventCreativeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmFloodlightActivityGroup': {
        'html': 'dcmFloodlightActivityGroupPage/dcmFloodlightActivityGroupPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCreativeType': {
        'html': 'dcmClickCreativeTypePage/dcmClickCreativeTypePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCampaignId': {
        'html': 'dcmClickCampaignIdPage/dcmClickCampaignIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCreativeTypeId': {
        'html': 'dcmClickCreativeTypeIdPage/dcmClickCreativeTypeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickAdvertiserId': {
        'html': 'dcmClickAdvertiserIdPage/dcmClickAdvertiserIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickCreativeId': {
        'html': 'dcmClickCreativeIdPage/dcmClickCreativeIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventSpotId': {
        'html': 'dcmLastEventSpotIdPage/dcmLastEventSpotIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmClickSitePlacement': {
        'html': 'dcmClickSitePlacementPage/dcmClickSitePlacementPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventCreative': {
        'html': 'dcmLastEventCreativePage/dcmLastEventCreativePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:dcmLastEventRenderingId': {
        'html': 'dcmLastEventRenderingIdPage/dcmLastEventRenderingIdPage.html',
        'value': False,
        'view': 'Dimensions'},

    'ga:dcmFloodlightQuantity': {
        'html': 'dcmFloodlightQuantityPage/dcmFloodlightQuantityPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmRPC': {
        'html': 'dcmRPCPage/dcmRPCPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmCost': {
        'html': 'dcmCostPage/dcmCostPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmClicks': {
        'html': 'dcmClicksPage/dcmClicksPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmCTR': {
        'html': 'dcmCTRPage/dcmCTRPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmMargin': {
        'html': 'dcmMarginPage/dcmMarginPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmFloodlightRevenue': {
        'html': 'dcmFloodlightRevenuePage/dcmFloodlightRevenuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmROI': {
        'html': 'dcmROIPage/dcmROIPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmCPC': {
        'html': 'dcmCPCPage/dcmCPCPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:dcmImpressions': {
        'html': 'dcmImpressionsPage/dcmImpressionsPage.html',
        'value': False,
        'view': 'Metrics'}
}

audience_metrics = {
    'ga:userAgeBracket': {
        'html': 'userAgeBracketPage/userAgeBracketPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:interestInMarketCategory': {
        'html': 'interestInMarketCategoryPage/interestInMarketCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:userGender': {
        'html': 'userGenderPage/userGenderPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:interestOtherCategory': {
        'html': 'interestOtherCategoryPage/interestOtherCategoryPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:interestAffinityCategory': {
        'html': 'interestAffinityCategoryPage/interestAffinityCategoryPage.html',
        'value': False,
        'view': 'Dimensions'}
}

adsense_metrics = {
    'ga:adsenseAdUnitsViewed': {
        'html': 'adsenseAdUnitsViewedPage/adsenseAdUnitsViewedPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseAdsClicks': {
        'html': 'adsenseAdsClicksPage/adsenseAdsClicksPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsensePageImpressions': {
        'html': 'adsensePageImpressionsPage/adsensePageImpressionsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseCTR': {
        'html': 'adsenseCTRPage/adsenseCTRPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseRevenue': {
        'html': 'adsenseRevenuePage/adsenseRevenuePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseExits': {
        'html': 'adsenseExitsPage/adsenseExitsPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseAdsViewed': {
        'html': 'adsenseAdsViewedPage/adsenseAdsViewedPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:adsenseECPM': {
        'html': 'adsenseECPMPage/adsenseECPMPage.html',
        'value': False,
        'view': 'Metrics'}
}

channel_grouping_metrics = {
    'ga:channelGrouping': {
        'html': 'channelGroupingPage/channelGroupingPage.html',
        'value': False,
        'view': 'Dimensions'}}

related_products_metrics = {
    'ga:queryProductId': {
        'html': 'queryProductIdPage/queryProductIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:queryProductVariation': {
        'html': 'queryProductVariationPage/queryProductVariationPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:correlationModelId': {
        'html': 'correlationModelIdPage/correlationModelIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:relatedProductName': {
        'html': 'relatedProductNamePage/relatedProductNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:queryProductName': {
        'html': 'queryProductNamePage/queryProductNamePage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:relatedProductId': {
        'html': 'relatedProductIdPage/relatedProductIdPage.html',
        'value': False,
        'view': 'Dimensions'},
    'ga:relatedProductVariation': {
        'html': 'relatedProductVariationPage/relatedProductVariationPage.html',
        'value': False,
        'view': 'Dimensions'},

    'ga:relatedProductQuantity': {
        'html': 'relatedProductQuantityPage/relatedProductQuantityPage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:correlationScore': {
        'html': 'correlationScorePage/correlationScorePage.html',
        'value': False,
        'view': 'Metrics'},
    'ga:queryProductQuantity': {
        'html': 'queryProductQuantityPage/queryProductQuantityPage.html',
        'value': False,
        'view': 'Metrics'}
}